#Products available
- name: 'Write & Improve'
  content: 'Get feedback on your writing in seconds!'
  link: '/products/write-and-improve'

# - name: 'Speak & Improve'
#   content: 'Develop your fermentum, nulla luctus pharetra'
#   link: '/products/speak-and-improve'

- name: 'API'
  content: 'Embed ELíT’s technology in your own products.'
  link: '/products/api'